;;; worktrees-workflows-test.el --- Workflow stories as ERT tests -*- lexical-binding: t; -*-

;;; Commentary:
;; High-level, user-story-driven tests that exercise the vibemacs worktrees UX.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'worktrees-core)
(require 'worktrees-dashboard)
(require 'worktrees-layout)
(require 'worktrees-process)
(require 'worktrees-chat)
(require 'worktrees-git-status)

(ert-deftest vibemacs-startup-shows-home-layout ()
  "First launch should render the home layout with the welcome buffer."
  (let ((vibemacs-worktrees-startup-layout t)
        (vibemacs-worktrees--startup-applied nil)
        (vibemacs-worktrees--dashboard-window nil)
        (vibemacs-worktrees--center-window nil)
        (vibemacs-worktrees--right-window nil)
        (vibemacs-worktrees--terminal-window nil))
    (save-window-excursion
      (vibemacs-worktrees-launch-home)
      (should vibemacs-worktrees--startup-applied)
      (should (get-buffer vibemacs-welcome-buffer))
      (should (eq (window-buffer (or vibemacs-worktrees--center-window
                                     (selected-window)))
                  (get-buffer vibemacs-welcome-buffer))))))

(ert-deftest vibemacs-dashboard-add-project-dispatches ()
  "\"+ Add Project\" row should invoke project registration."
  (let (called)
    (with-temp-buffer
      (require 'tabulated-list)
      (tabulated-list-mode)
      (let ((inhibit-read-only t))
        (insert "Add Project\n")
        (add-text-properties (point-min) (1+ (point-min))
                             '(tabulated-list-id (:add-project . nil))))
      (goto-char (point-min))
      (cl-letf (((symbol-function 'vibemacs-project-add)
                 (lambda (&rest _) (interactive) (setq called t))))
        (vibemacs-worktrees-dashboard-enter)))
    (should called)))

(ert-deftest vibemacs-create-worktree-uses-name-and-runs-setup ()
  "Creating a worktree names branch/path after the provided worktree name and runs setup."
  (let* ((repo (make-temp-file "vibemacs-repo" t))
         (vibemacs-worktrees-root (make-temp-file "vibemacs-root" t))
         (vibemacs-worktrees-open-terminal-on-create nil)
         (git-calls nil)
         (setup-call nil)
         entry)
    (unwind-protect
        (cl-letf (((symbol-function 'vibemacs-worktrees--current-repo)
                   (lambda () repo))
                  ((symbol-function 'vibemacs-worktrees--read-worktree-name)
                   (lambda () "demo"))
                  ((symbol-function 'vibemacs-worktrees--call-git)
                   (lambda (_repo &rest args)
                     (push args git-calls)
                     ""))
                  ((symbol-function 'vibemacs-worktrees--register) #'ignore)
                  ((symbol-function 'vibemacs-worktrees--save-metadata) #'ignore)
                  ((symbol-function 'vibemacs-worktrees--default-metadata)
                   (lambda (_entry) '((assistant . "codex"))))
                 ((symbol-function 'vibemacs-worktrees--activate-workspace-layout) #'ignore)
                 ((symbol-function 'vibemacs-worktrees-center-show-terminal) #'ignore)
                 ((symbol-function 'vibemacs-worktrees-center-show-chat) #'ignore)
                 ((symbol-function 'completing-read) (lambda (&rest _) "codex"))
                 ((symbol-function 'vibemacs-worktrees--run-setup-commands)
                  (lambda (repo-path target name on-success on-failure)
                    (setq setup-call (list repo-path target name
                                           (functionp on-success)
                                            (functionp on-failure))))))
          (setq entry (vibemacs-worktrees-new))
      (delete-directory repo t)
      (delete-directory vibemacs-worktrees-root t))
    (let* ((expected (expand-file-name "demo"
                                       (expand-file-name
                                        (file-name-nondirectory (directory-file-name repo))
                                        vibemacs-worktrees-root))))
      (should (equal (vibemacs-worktrees--entry-root entry) expected))
      (should (equal (vibemacs-worktrees--entry-branch entry) "demo"))
      (should (member (list "worktree" "add" "-b" "demo" expected "origin/main")
                      git-calls))
      (should (equal (cl-subseq setup-call 0 3) (list repo expected "demo")))))))

(ert-deftest vibemacs-activate-workspace-builds-three-pane-layout ()
  "Selecting a worktree should build the dashboard/chat/git-status+terminal layout."
  (let* ((entry (vibemacs-worktrees--entry-create
                 :name "demo" :branch "demo" :repo "/tmp/repo"
                 :root "/tmp/repo/worktrees/demo" :base "origin/main"
                 :created "2025-01-01T00:00:00Z"))
         (vibemacs-worktrees--dashboard-window nil)
         (vibemacs-worktrees--center-window nil)
         (vibemacs-worktrees--right-window nil)
         (vibemacs-worktrees--terminal-window nil)
         (activated nil)
         (chat-called nil)
         (status-called nil)
         (auto-called nil)
         (vibemacs-worktrees--startup-applied nil))
    (save-window-excursion
      (ignore-errors (set-frame-size (selected-frame) 200 60))
      (cl-letf (((symbol-function 'vibemacs-worktrees--desired-widths)
                 (lambda (_frame-width)
                   (list :mode 'three :sidebar 30 :dashboard 30 :min-chat 60 :frame 200)))
                ((symbol-function 'vibemacs-worktrees-dashboard--setup-buffer)
                 (lambda () (get-buffer-create "*dash-test*")))
                ((symbol-function 'vibemacs-worktrees-git-status--setup-buffer)
                 (lambda () (get-buffer-create "*status-test*")))
                ((symbol-function 'vibemacs-worktrees-dashboard--activate)
                 (lambda (_entry) (setq activated t)))
                ((symbol-function 'vibemacs-worktrees-center-show-chat)
                 (lambda (_entry) (setq chat-called t)))
                ((symbol-function 'vibemacs-worktrees-git-status--populate)
                 (lambda (_entry) (setq status-called t)))
                ((symbol-function 'vibemacs-worktrees-git-status--start-auto-refresh)
                 (lambda () (setq auto-called t)))
                ((symbol-function 'vibemacs-worktrees--right-terminal-buffer)
                 (lambda (_entry) (get-buffer-create "*term-test*"))))
        (vibemacs-worktrees--activate-workspace-layout entry))
      (should activated)
      (should chat-called)
      (should status-called)
      (should auto-called)
      (should (window-live-p vibemacs-worktrees--dashboard-window))
      (should (window-live-p vibemacs-worktrees--center-window))
      (should (window-live-p vibemacs-worktrees--right-window))
      (should (window-live-p vibemacs-worktrees--terminal-window))
      (should (eq (window-buffer vibemacs-worktrees--dashboard-window)
                  (get-buffer "*dash-test*")))
      (should (eq (window-buffer vibemacs-worktrees--right-window)
                  (get-buffer "*status-test*")))
      (should (eq (window-buffer vibemacs-worktrees--terminal-window)
                  (get-buffer "*term-test*")))
      (should vibemacs-worktrees--startup-applied))))

(ert-deftest vibemacs-create-agent-tab-adds-center-tab ()
  "Adding a new agent tab should create a buffer and add it to center tabs."
  (let* ((root (make-temp-file "vibemacs-worktree" t))
         (entry (vibemacs-worktrees--entry-create
                 :name "demo" :branch "demo" :repo root :root root :base "" :created "ts"))
         (vibemacs-worktrees--explicit-tab-lists (make-hash-table :test 'equal))
         (vibemacs-worktrees--center-window (selected-window)))
    (set-window-parameter vibemacs-worktrees--center-window 'vibemacs-center-entry entry)
    (cl-letf (((symbol-function 'vibemacs-worktrees--ensure-vterm) (lambda () t))
              ((symbol-function 'vibemacs-worktrees--assistant-command) (lambda (_agent) "echo agent"))
              ((symbol-function 'vterm)
               (lambda () (get-buffer-create vterm-buffer-name))))
      (let ((buf (vibemacs-worktrees--create-agent-tab entry "codex" t)))
        (should buf)
        (should (member buf (window-parameter vibemacs-worktrees--center-window 'vibemacs-explicit-tabs)))
        (with-current-buffer buf
          (should (eq vibemacs-worktrees--buffer-role 'agent))
          (should (string= (expand-file-name vibemacs-worktrees--buffer-root)
                           (expand-file-name (vibemacs-worktrees--entry-root entry)))))))))

(ert-deftest vibemacs-tabs-are-scoped-per-worktree ()
  "Each worktree keeps its own center-pane tab set when switching."
  (let* ((entry-a (vibemacs-worktrees--entry-create
                   :name "a" :branch "a" :repo "/tmp/repo-a"
                   :root "/tmp/repo-a/worktrees/a" :base "" :created "ts"))
         (entry-b (vibemacs-worktrees--entry-create
                   :name "b" :branch "b" :repo "/tmp/repo-b"
                   :root "/tmp/repo-b/worktrees/b" :base "" :created "ts"))
         (vibemacs-worktrees--explicit-tab-lists (make-hash-table :test 'equal))
         (vibemacs-worktrees--center-window (selected-window)))
    (set-window-parameter vibemacs-worktrees--center-window 'vibemacs-center-entry entry-a)
    (let ((buf-a (get-buffer-create "*tab-a*")))
      (vibemacs-worktrees--add-to-tabs buf-a)
      (set-window-parameter vibemacs-worktrees--center-window 'vibemacs-explicit-tabs nil)
      (set-window-parameter vibemacs-worktrees--center-window 'vibemacs-center-entry entry-b)
      (let ((buf-b (get-buffer-create "*tab-b*")))
        (vibemacs-worktrees--add-to-tabs buf-b)
        (let ((tabs-a (gethash (expand-file-name (vibemacs-worktrees--entry-root entry-a))
                               vibemacs-worktrees--explicit-tab-lists))
              (tabs-b (gethash (expand-file-name (vibemacs-worktrees--entry-root entry-b))
                               vibemacs-worktrees--explicit-tab-lists)))
          (should (member buf-a tabs-a))
          (should (member buf-b tabs-b))
          (should-not (member buf-a tabs-b)))))))

(ert-deftest vibemacs-git-status-open-file-opens-and-tabs ()
  "Selecting a file in git status should open it and add it as a center tab."
  (let* ((root (make-temp-file "vibemacs-git" t))
         (file (expand-file-name "README.md" root))
         (entry (vibemacs-worktrees--entry-create
                 :name "demo" :branch "demo" :repo root :root root :base "" :created "ts"))
         (vibemacs-worktrees--explicit-tab-lists (make-hash-table :test 'equal))
         (vibemacs-worktrees--center-window nil))
    (unwind-protect
        (save-window-excursion
          (with-temp-file file (insert "hello\n"))
          (setq vibemacs-worktrees--center-window (selected-window))
          (set-window-parameter vibemacs-worktrees--center-window 'vibemacs-center-entry entry)
          (let ((buffer (get-buffer-create vibemacs-worktrees-git-status-buffer)))
            (with-current-buffer buffer
              (erase-buffer)
              (insert (propertize " M README.md\n" 'vibemacs-file-path "README.md"))
              (goto-char (point-min)))
            (cl-letf (((symbol-function 'vibemacs-worktrees-center--current-entry)
                       (lambda () entry))
                      ((symbol-function 'diff-hl-mode) (lambda (&rest _) t))
                      ((symbol-function 'diff-hl-margin-mode) (lambda (&rest _) t))
                      ((symbol-function 'diff-hl-update) #'ignore)
                      ((symbol-function 'diff-hl-next-hunk) #'ignore))
              (with-current-buffer buffer
                (vibemacs-worktrees-git-status-open-file))))
          (let ((tabs (window-parameter vibemacs-worktrees--center-window 'vibemacs-explicit-tabs)))
            (should (cl-some (lambda (buf) (string= (buffer-file-name buf) file)) tabs))
            (should (string= (buffer-file-name (window-buffer vibemacs-worktrees--center-window))
                             file))))
      (delete-directory root t))))

(ert-deftest vibemacs-dashboard-delete-removes-and-returns-home ()
  "Deleting a worktree should remove checkout, drop the branch, and return home."
  (let* ((repo (make-temp-file "vibemacs-repo" t))
         (root (expand-file-name "demo" repo))
         (_ (make-directory root t))
         (entry (vibemacs-worktrees--entry-create
                 :name "demo" :branch "demo" :repo repo :root root :base "" :created "ts"))
         (calls nil)
         (home-called nil))
    (unwind-protect
        (cl-letf (((symbol-function 'vibemacs-worktrees-dashboard--current-entry)
                   (lambda () entry))
                  ((symbol-function 'vibemacs-worktrees--call-git)
                   (lambda (_repo &rest args) (push args calls) ""))
                  ((symbol-function 'shell-command)
                   (lambda (&rest _) (push 'rm calls)))
                  ((symbol-function 'vibemacs-worktrees--metadata-path)
                   (lambda (_entry) (expand-file-name "meta/metadata.json" root)))
                  ((symbol-function 'delete-directory)
                   (lambda (path recursive)
                     (push (list :delete path recursive) calls)))
                  ((symbol-function 'vibemacs-worktrees--unregister)
                   (lambda (arg) (push (list :unregister arg) calls)))
                  ((symbol-function 'vibemacs-worktrees-launch-home)
                   (lambda () (setq home-called t)))
                  ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
          (vibemacs-worktrees-dashboard-delete))
      (delete-directory repo t))
    (should home-called)
    (should (cl-some (lambda (call)
                       (and (listp call)
                            (equal call (list "worktree" "remove" "--force" root))))
                     calls))
    (should (cl-some (lambda (call)
                       (and (listp call)
                            (equal call '("branch" "-D" "demo"))))
                     calls))
    (should (member (list :unregister root) calls))))

(ert-deftest vibemacs-leader-binds-agent-and-window-nav ()
  "Key chords should launch new agent tab and window navigation."
  (let ((inhibit-message t)
        (load-prefer-newer t))
    (load (expand-file-name "init.el" user-emacs-directory) nil 'nomessage)
    (dolist (pair '(("SPC v a n" . vibemacs-worktrees-new-agent-tab)
                    ("SPC v t n" . vibemacs-worktrees-new-terminal-tab)
                    ("SPC v n" . vibemacs-worktrees-smart-next-tab)
                    ("SPC v p" . vibemacs-worktrees-smart-prev-tab)
                    ("SPC w h" . windmove-left)
                    ("SPC w j" . windmove-down)
                    ("SPC w k" . windmove-up)
                    ("SPC w l" . windmove-right)))
      (should (eq (key-binding (kbd (car pair))) (cdr pair))))))

(provide 'worktrees-workflows-test)
;;; worktrees-workflows-test.el ends here
